server:
  port: 8001
spring:
  application:
    name: userServer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
  register-with-eureka: true
  fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
test.name:bob
